# Generated by Django 5.2.5 on 2025-08-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mock', 'Mock'), ('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('cod', 'Cash on Delivery')], default='mock', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NPR', max_length=8)),
                ('status', models.CharField(default='created', max_length=16)),
                ('provider_order_id', models.CharField(blank=True, default='', max_length=64)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=64)),
                ('provider_signature', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_payments', related_query_name='gateway_payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Gateway Payment',
                'verbose_name_plural': 'Gateway Payments',
            },
        ),
    ]
