# Generated by Django 5.1.3 on 2025-08-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('mock', 'Mock'), ('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('cod', 'Cash on Delivery')], default='mock', max_length=16),
        ),
    ]
