# Generated by Django 5.1.3 on 2025-08-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicesequence',
            options={'verbose_name': 'Invoice Sequence', 'verbose_name_plural': 'Invoice Sequences'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Billing Payment', 'verbose_name_plural': 'Billing Payments'},
        ),
        migrations.AlterModelOptions(
            name='paymentreceipt',
            options={'verbose_name': 'Payment Receipt', 'verbose_name_plural': 'Payment Receipts'},
        ),
        migrations.RenameField(
            model_name='paymentreceipt',
            old_name='generated_at',
            new_name='issued_at',
        ),
        migrations.AlterUniqueTogether(
            name='invoicesequence',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='order',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='receipt_file',
        ),
        migrations.AddField(
            model_name='invoicesequence',
            name='last_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='NPR', max_length=8),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='created', max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', related_query_name='receipt', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoicesequence',
            name='prefix',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_payments', related_query_name='billing_payment', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.RemoveField(
            model_name='invoicesequence',
            name='location',
        ),
        migrations.RemoveField(
            model_name='invoicesequence',
            name='next_number',
        ),
        migrations.RemoveField(
            model_name='invoicesequence',
            name='padding',
        ),
        migrations.RemoveField(
            model_name='invoicesequence',
            name='updated_at',
        ),
    ]
